title: Jane的个人博客
email: your-email@example.com
description: Jane的个人技术与生活博客
baseurl: ""
url: "https://janemiraitowa.github.io"
github_username: JaneMiraitowa

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap

# 文章摘要
excerpt_separator: <!--more-->

# 分类
collections:
  category:
    output: true
    permalink: /category/:name/